# Generated by Django 2.2.2 on 2019-12-20 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info_exercices',
            name='cals_burn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='info_exercices',
            name='kmR',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='info_month',
            name='cals_burn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='info_month',
            name='kmR',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='info_rutine',
            name='cals_burn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='info_rutine',
            name='kmR',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='info_sessions',
            name='cals_burn',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='info_sessions',
            name='intensity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='info_sessions',
            name='kmR',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='info_sessions',
            name='time',
            field=models.TimeField(null=True),
        ),
    ]
