# Generated by Django 2.2.2 on 2019-12-24 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('information', '0002_auto_20191220_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='info_exercices',
            name='dur_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='info_exercices',
            name='kmr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='info_exercices',
            name='ptRute',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='info_exercices',
            name='ritcard',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='info_exercices',
            name='steps',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='info_month',
            name='dur_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='info_month',
            name='kmr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='info_month',
            name='ptRute',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='info_month',
            name='ritcard',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='info_month',
            name='steps',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='info_rutine',
            name='dur_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='info_rutine',
            name='kmr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='info_rutine',
            name='ptRute',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='info_rutine',
            name='ritcard',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='info_rutine',
            name='steps',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='info_sessions',
            name='dur_time',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='info_sessions',
            name='kmr',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='info_sessions',
            name='ptRute',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='info_sessions',
            name='ritcard',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='info_sessions',
            name='steps',
            field=models.IntegerField(null=True),
        ),
    ]
