# Generated by Django 2.2.2 on 2019-12-13 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0002_auto_20191213_0241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rutine',
            name='info_rutine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='information.Info_rutine'),
        ),
    ]
