# Generated by Django 2.2.2 on 2019-12-14 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_auto_20191213_1741'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='sessions',
        ),
        migrations.AddField(
            model_name='profile',
            name='rutines',
            field=models.ManyToManyField(to='exercises.Rutine'),
        ),
    ]
